site_name: py-blog 文档
site_author: zcmimi
copyright: Copyright &copy; 2019 - 2020 zcmimi
theme:
  name: material
  language: 'zh'
  palette:
    scheme: default
    primary: blue
    accent: red
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

repo_url: https://github.com/zcmimi/py-blog
nav:
  - 关于: index.md
  - 快速开始: 快速开始.md
  - 自定义配置: 自定义配置.md
  - 开始写作: 开始写作.md
  - 资源文件夹: 资源文件夹.md
  - 博客生成流程: 博客生成流程.md
  - 部署: 部署.md
  - 主题: 主题.md
  - 动态服务器: 动态服务器.md

  - 开发主题:
    - 开发主题: develop_theme/开发主题.md
    - setting.yml: develop_theme/setting.yml.md
    - 预设变量名与含义: develop_theme/变量名与含义.md
    - markdown: develop_theme/markdown.md